#!/bin/sh
clear
echo "Loading..."
export SDL_NOMOUSE=1
export HOME=/usr/local/home
cd /usr/local/sbin

if [ "$1" = "" ]
then
ARG="menu"
else
ARG="$@"
fi
CONTROL=0
CURRENT=1
TOTAL=0
while read line
do TOTAL=`expr $TOTAL + 1`
done < "$ARG"
TOTAL=`expr $TOTAL + 1`
draw_logo()
{
clear
echo "-----------------------------------"
echo "+       m i c r o M e n u         +"
echo "-----------------------------------"
echo ""
echo "Dpad UP and Dpad DOWN to move cursor"
echo "Dpad RIGHT to select the item"
echo "Dpad LEFT to step down 5 items"
echo "Dpad UP on first position to go back"
echo "to main menu(while in a submenu)"
echo "-----------------------------------"
}
draw_menu()
{
i=$CURRENT
while [ $i != `expr $CURRENT + 25` ]; do
	if [ $i -le $TOTAL ]
	then
	item=$(head -n `expr $i` "$ARG" | tail -n 1)
		if [ $i -eq $CURRENT ]
		then
		echo ">" `echo $item | cut -d\| -f1`
		else
		echo " " `echo $item | cut -d\| -f1`
		fi
	else
	echo ""
	fi
	i=`expr $i + 1`
done
}
check_input()
{
if [ "$pressed" = "[A" ]
	then
		if [ $CURRENT -gt 1 ]
			then CURRENT=`expr $CURRENT - 1`
		else
			if [ "$ARG" != "main" ]
			then
			cd /usr/local/sbin
			./main
			fi
		fi
	fi
	if [ "$pressed" = "[B" ]
	then
		if [ $CURRENT -lt $TOTAL ]
			then CURRENT=`expr $CURRENT + 1`
		fi
	echo "$CURRENT"
	fi
	if [ "$pressed" = "[C" ]
	then
		item=$(head -n `expr $CURRENT` "$ARG" | tail -n 1)
		item=`echo $item | tr '	' ' '`
		if [ "`echo $item | cut -d\| -f4`" == "--keep" ]
		then
			while true
			do
				cd `echo $item | cut -d\| -f2`
				`echo $item | cut -d\| -f3`
			done
		fi
		cd `echo $item | cut -d\| -f2`
		`echo $item | cut -d\| -f3`
		pressed="X"
	fi
	if [ "$pressed" = "[D" ]
	then
		if [ 5 lt $TOTAL ]
		then
			CURRENT=`expr $CURRENT + 5`
			if [ $CURRENT -ge $TOTAL ]
			then
			CURRENT=`expr $CURRENT - $TOTAL`
			fi
		fi
	fi
}
check_input
while [ "$pressed" != "X" ]
do
draw_logo
draw_menu
read -n 3 pressed
check_input
done
