#!/bin/sh
clear
echo "Loading..."
export SDL_NOMOUSE=1
export HOME=/usr/local/home
cd /usr/local/sbin

if [ "$1" = "" ]
then
#AAAAAAAAARG! CAPTAIN
ARG="menu"
else
ARG="$@"
fi
CONTROLE=0
ATUAL=1
TOTAL=0
while read line
do TOTAL=`expr $TOTAL + 1`
done < "$ARG"
TOTAL=`expr $TOTAL + 1`
draw_logo()
{
clear
echo "-----------------------------------"
echo "+       m i c r o M e n u         +"
echo "-----------------------------------"
echo ""
echo "Dpad UP and Dpad DOWN to move cursor"
echo "Dpad RIGHT to select the item"
echo "Dpad LEFT to step down 5 itens"
echo "Dpad UP on first position to go back"
echo "to main menu(while in subs)"
echo "-----------------------------------"
}
draw_menu()
{
i=$ATUAL
while [ $i != `expr $ATUAL + 25` ]; do
	if [ $i -le $TOTAL ] 
	then
	item=$(head -n `expr $i` "$ARG" | tail -n 1)
		if [ $i -eq $ATUAL ] 
		then
		echo ">" `echo $item | cut -d\| -f1` 
		else
		echo " " `echo $item | cut -d\| -f1` 
		fi
	else 
	echo ""
	fi
	i=`expr $i + 1`
done
}
check_input()
{
if [ "$pressionada" = "[A" ] 
	then 
		if [ $ATUAL -gt 1 ]
			then ATUAL=`expr $ATUAL - 1`
		else
			if [ "$ARG" != "main" ]
			then
			cd /usr/local/sbin
			./main
			fi
		fi
	fi
	if [ "$pressionada" = "[B" ]
	then
		if [ $ATUAL -lt $TOTAL ]
			then ATUAL=`expr $ATUAL + 1`
		fi
	echo "$ATUAL"
	fi
	if [ "$pressionada" = "[C" ]
	then
		item=$(head -n `expr $ATUAL` "$ARG" | tail -n 1)
		item=`echo $item | tr '	' ' '`
		if [ "`echo $item | cut -d\| -f4`" == "--keep" ]
		then
			while true
			do
				cd `echo $item | cut -d\| -f2` 
				`echo $item | cut -d\| -f3` 
			done
		fi
		cd `echo $item | cut -d\| -f2` 
		`echo $item | cut -d\| -f3`
		pressionada="X"
	fi
	if [ "$pressionada" = "[D" ]
	then
		if [ 5 lt $TOTAL ]
		then
			ATUAL=`expr $ATUAL + 5`
			if [ $ATUAL -ge $TOTAL ]
			then
			ATUAL=`expr $ATUAL - $TOTAL`
			fi
		fi
	fi
}
check_input
while [ "$pressionada" != "X" ]
do
draw_logo
draw_menu
read -n 3 pressionada
check_input
done 